SEQUENCE_INPUT_OPTIONS = ["Peptide", "Formula", "Mass"]
DEFAULT_INPUT = "Peptide"
DEFAULT_INPUT_INDEX = SEQUENCE_INPUT_OPTIONS.index(DEFAULT_INPUT)
DEFAULT_SEQUENCE = "PEPTIDE"
DEFAULT_FORMULA = "C6H12O6"

ION_TYPES = ["a", "b", "c", "x", "y", "z", "p", "i"]
DEFAULT_ION_TYPE = "p"
DEFAULT_ION_TYPE_INDEX = ION_TYPES.index(DEFAULT_ION_TYPE)

DEFAULT_MASS = 1000.0
MAX_MASS = 100_001.0
MIN_MASS = 0.0
MASS_STEP = 100.0

DEFAULT_CHARGE = 1
MIN_CHARGE = 1
MAX_CHARGE = 10
CHARGE_STEP = 1

DEFAULT_ISOTOPES = 100
MIN_ISOTOPES = 1
MAX_ISOTOPES = 200
ISOTOPES_STEP = 1

ABUNDANCE_OPTIONS = [0.00001, 0.0001, 0.001, 0.01, 0.1]
DEFAULT_ABUNDANCE = 0.0001
DEFAULT_ABUNDANCE_INDEX = ABUNDANCE_OPTIONS.index(DEFAULT_ABUNDANCE)

DEFAULT_USE_NEUTRON = True

DEFAULT_DISTRIBUTION_RESOLUTION = 2
MIN_DISTRIBUTION_RESOLUTION = 0
MAX_DISTRIBUTION_RESOLUTION = 10
DISTRIBUTION_RESOLUTION_STEP = 1

# Neutron mass options
NEUTRON_MASS_OPTIONS = ["Neutron", "C13-C12", "Averagine (Peptide)", "Custom"]
DEFAULT_NEUTRON_MASS_OPTION = "Averagine (Peptide)"
DEFAULT_NEUTRON_MASS_INDEX = NEUTRON_MASS_OPTIONS.index(DEFAULT_NEUTRON_MASS_OPTION)

# Neutron mass values
NEUTRON_MASS_VALUE = 1.00866491597  # Neutron mass in Da
C13_C12_DIFF = 1.00335  # Mass difference between C13 and C12
AVERAGINE_MASS = 1.002856  # Averagine mass shift for peptides

DEFAULT_IS_INTENSITY_SUM = False